name: Firts workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Hello Wordl of Cats
        run: echo "Hello !! from ${{ github.workflow }} trigerred by the ${{ github.event_name }} by me ${{ github.actor }}"
